#!/usr/bin/env node
/**
 * Downloads a logo for every Robinhood stock token on Robinhood Chain (4663) into public/logos/assets/<address>.svg
 * and writes indexer/asset-logos.ts (the list the indexer serves). Robinhood's own API returns the same generic
 * Robinhood logo for every stock token, so the company logo comes from TradingView, matched by the token's ISIN
 * (ticker on a US listing as a fallback, reported for review).
 *
 * Run from web/: node scripts/asset-logos.mjs   (re-run when Robinhood lists new stock tokens)
 */
import fs from "node:fs";
import path from "node:path";

const CHAIN_ID = 4663;
const OUT_DIR = path.join("public", "logos", "assets");
const LIST_FILE = path.join("indexer", "asset-logos.ts");
const TV_HEADERS = { Origin: "https://www.tradingview.com", Referer: "https://www.tradingview.com/", "User-Agent": "Mozilla/5.0" };
const US = new Set(["NASDAQ", "NYSE", "AMEX", "NYSE ARCA", "CBOE", "BATS", "OTC"]);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function json(url, headers = {}) {
  for (let i = 0; i < 4; i++) {
    const res = await fetch(url, { headers, signal: AbortSignal.timeout(15_000) }).catch(() => null);
    if (res?.ok) return res.json();
    await sleep(1_000 * (i + 1));
  }
  throw new Error(`GET ${url} failed`);
}

const search = (text) =>
  json(
    `https://symbol-search.tradingview.com/symbol_search/v3/?text=${encodeURIComponent(text)}&hl=0&exchange=&lang=en&search_type=undefined&domain=production`,
    TV_HEADERS,
  ).then((j) => (j.symbols ?? j).map((s) => ({ ...s, symbol: String(s.symbol).replace(/<\/?em>/g, "") })));

/** The listing whose logo we take: same ISIN (primary listing first), else the same ticker on a US exchange. */
async function findLogoId(stock) {
  if (stock.isin) {
    const hits = (await search(stock.isin)).filter((s) => s.isin === stock.isin && s.logoid);
    const best = hits.find((s) => s.is_primary_listing) ?? hits.find((s) => s.country === "US") ?? hits[0];
    if (best) return { logoid: best.logoid, via: "isin", listing: `${best.exchange}:${best.symbol} ${best.description}` };
  }
  const hits = (await search(stock.symbol)).filter((s) => s.symbol === stock.symbol && s.logoid && US.has(s.exchange));
  const best = hits[0];
  return best ? { logoid: best.logoid, via: "ticker", listing: `${best.exchange}:${best.symbol} ${best.description}` } : null;
}

/** Plain vector only: logos are served from the site's own origin, so nothing that can run or load anything. */
function safeSvg(svg) {
  return (
    /^\s*(<!--[^]*?-->\s*)?<svg[\s>]/i.test(svg) &&
    !/<script|<foreignObject|<iframe|<!ENTITY|<!DOCTYPE|\son\w+\s*=|javascript:|(?:xlink:)?href\s*=\s*["'](?!#)/i.test(svg)
  );
}

async function downloadSvg(logoid) {
  for (const name of [`${logoid}--big`, logoid]) {
    const res = await fetch(`https://s3-symbol-logo.tradingview.com/${name}.svg`, { signal: AbortSignal.timeout(15_000) }).catch(() => null);
    if (res?.ok) return res.text();
  }
  return null;
}

const rh = await json("https://api.robinhood.com/rhj/assets");
const stocks = [];
for (const a of rh.assets ?? []) {
  const d = (a.deployments ?? []).find((x) => x.chainId === CHAIN_ID && x.contractAddress);
  if (!d || !a.tokenSymbol) continue;
  stocks.push({
    address: d.contractAddress.toLowerCase(),
    symbol: a.tokenSymbol,
    name: (a.tokenName ?? a.tokenSymbol).replace(/\s*[•·]\s*Robinhood Token$/i, ""),
    isin: a.isin ?? null,
  });
}
stocks.sort((x, y) => x.symbol.localeCompare(y.symbol));
console.log(`${stocks.length} Robinhood stock tokens on chain ${CHAIN_ID}`);

fs.mkdirSync(OUT_DIR, { recursive: true });
const saved = [];
const review = [];
const missing = [];
for (const s of stocks) {
  const found = await findLogoId(s).catch((e) => (console.error(s.symbol, e.message), null));
  const svg = found && (await downloadSvg(found.logoid));
  if (!found || !svg || !safeSvg(svg)) {
    missing.push(`${s.symbol} (${s.name})${found && svg ? " — rejected SVG" : ""}`);
    continue;
  }
  fs.writeFileSync(path.join(OUT_DIR, `${s.address}.svg`), svg.trim() + "\n");
  saved.push(s);
  if (found.via !== "isin") review.push(`${s.symbol} (${s.name}) → ${found.listing} [${found.logoid}]`);
  await sleep(150);
}

const lines = saved.map((s) => `  "${s.address}", // ${s.symbol} · ${s.name.replace(/\*\//g, "")}`);
fs.writeFileSync(
  LIST_FILE,
  `// Generated by scripts/asset-logos.mjs — do not edit by hand.
/** Robinhood stock tokens with a logo in public/logos/assets/<address>.svg. */
export const ASSET_LOGOS: ReadonlySet<string> = new Set([
${lines.join("\n")}
]);
`,
);

console.log(`saved ${saved.length}, missing ${missing.length}`);
if (review.length) console.log(`matched by ticker (check):\n  ${review.join("\n  ")}`);
if (missing.length) console.log(`no logo:\n  ${missing.join("\n  ")}`);
