// Writes packages/shared/src/abi.generated.ts from Foundry artifacts. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../", import.meta.url).pathname;
const pick = (name) => JSON.parse(readFileSync(`${root}out/${name}.sol/${name}.json`, "utf8")).abi;
const out = [
  "// Generated by contracts/script/export-abi.mjs from Foundry artifacts — do not edit.",
  `export const launchpadAbi = ${JSON.stringify(pick("Launchpad"), null, 2)} as const;`,
  `export const lockerAbi = ${JSON.stringify(pick("LiquidityLocker"), null, 2)} as const;`,
  "",
].join("\n\n");
writeFileSync(`${root}../packages/shared/src/abi.generated.ts`, out);
console.log("wrote packages/shared/src/abi.generated.ts");
