// Generated by scripts/asset-logos.mjs — do not edit by hand.
/** Robinhood stock tokens with a logo in public/logos/assets/<address>.svg. */
export const ASSET_LOGOS: ReadonlySet<string> = new Set([
  "0x521cf887e6531c6f667b5bc4d896e5d9bfe8eb2e", // AAOI · Applied Optoelectronics
  "0xaf3d76f1834a1d425780943c99ea8a608f8a93f9", // AAPL · Apple
  "0x3139d77ace0cbaa5bdfd38bd1f1911a794af0b0e", // ABCL · Abcellera Biologics
  "0x232b8ed6377be97813853b0ac104c4cda8378d1b", // ADBE · Adobe
  "0x5f604fba1162193a4388a5dfa56f556f3e133cc2", // AEHR · Aehr
  "0xfaf9cb261b5fcc1f404bb10cd39c5c6c1974e612", // AEIS · Advanced Energy
  "0x748c32c3ca24edf31ea597db1f3d330a7a6da3dc", // ALAB · Astera Labs, Inc.
  "0x36046893810a7e7fce501229d57dc3fc8c8716d0", // AMAT · Applied Materials
  "0x99d9d8663545151603863c5acbd6fc3218899009", // AMBA · Ambarella
  "0x05a3d1cd21d0c88145e82600e62e7e496e0f222b", // AMC · AMC Entertainment
  "0x86923f96303d656e4aa86d9d42d1e57ad2023fdc", // AMD · AMD
  "0xdd356aa38f40a7b7076755ac854b6fbb1f0d305b", // AMKR · Amkor Technology
  "0x12f190a9f9d7d37a250758b26824b97ce941bf54", // AMZN · Amazon
  "0x28babd556b60e53663b8615036479a29c2cdd1bf", // ANET · Arista
  "0xb8dbf92f9741c9ac1c32115e78581f23509916fd", // APLD · Applied Digital
  "0xa249baf1063af884807c1e1400aef7784836917e", // APP · AppLovin
  "0x47f93d52cbec7c6d2cfc080e154002370a60daea", // ASML · ASML Holding NV
  "0x1af6446f07eb1d97c546afc8c9544cbdf3ad5137", // ASTS · AST SpaceMobile
  "0x373c06c4f7bde527d7dae4ba169e42b55e393ced", // AUR · Aurora Innovation
  "0xf6290b5e7c26502e2da514c31509849718ea76a5", // AVAV · AeroVironment
  "0x156e175dd063a8ce274c50654ef40e0032b3fbcf", // AVGO · Broadcom
  "0xc27dbd474af5181c5a8777903690d8d262d12648", // AXON · Axon
  "0x141eea040c2250eec0314e336975e81f85f6585e", // AXTI · AXT
  "0x4d21483a44bf67a86b77e3da301411880797d452", // BA · Boeing
  "0xad25ac6c84d497db898fa1e8387bf6af3532a1c4", // BABA · Alibaba
  "0x48e39e56acdba37b09020c0b734a613c9a2f100a", // BB · Blackberry
  "0x822cc93ffd030293e9842c30bbd678f530701867", // BE · Bloom Energy
  "0x2f62fc9fabb470c690f141c28340ed832bb27020", // BND · Vanguard Total Bond Market ETF
  "0xcef9027c7d6985b85f0ba431125073529a947a68", // BULL · Webull
  "0x5c90450bbb4273d7b2f17cf6917aeb237a569679", // CBRS · Cerebras Systems
  "0x9651342cea770ae9a2969ba2a52611523146aef9", // CCL · Carnival Corporation
  "0xae517a2903e68bd929dfd15be875f8369d53e94a", // CEG · Constellation Energy
  "0x8cf07c5a878945185d327aaa6e33faa95f95e7bf", // CELH · Celsius
  "0x44f6d488021f8233b9416294d1fe9b1fee28382d", // CIEN · Ciena
  "0x62200915e7deab1ec7f79fb246dadbb80eacddd0", // CLOV · Clover Health Investments
  "0xbf449977089c718c004a66c554b26b94ef3ad4de", // CLS · Celestica
  "0xcbb95bbf36099d34da091dc6fa6f49efa257cee3", // CLSK · CleanSpark
  "0x92f9f459f1a9a5ad266b182be7bffd1c6c666894", // COHR · Coherent
  "0x6330d8c3178a418788df01a47479c0ce7ccf450b", // COIN · Coinbase
  "0x4ea005168d7f09a7a0ba9d1def21a479950e44c2", // COST · Costco
  "0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5", // CRCL · Circle Internet Group
  "0x4d67253bc223e6b0e104f1084c1fb2b669ddc41b", // CRDO · Credo Technology Group
  "0xd95b44124e475743a7589e68f3d74008a5536d44", // CRM · Salesforce
  "0xea72ecca2d0f6bfa1394dbbcff85b52cd4233931", // CRWD · CrowdStrike Holdings
  "0x5f10a1c971b69e47e059e1dc91901b59b3fb49c3", // CRWV · CoreWeave
  "0xf543967eebb6f1917992ef0e68de63ab07a5a0da", // CSCO · Cisco Systems
  "0x63d5a3b6939a33f1e75d8bcd85759858239600db", // CTSH · Cognizant
  "0xa4f319104089fe321dc8093c6e707d4fe190a988", // CVNA · Carvana
  "0x27c99fbde9d0d2aa4f4bfb4943f237843ddf6958", // DDOG · Datadog
  "0x941ae714ec6d8130c7b75d67160ca08f1e7d11dd", // DELL · Dell
  "0x1d11f0496982706c5e14a514d4e79f2e6bde4516", // DJT · Trump Media & Technology Group
  "0xc02f12b9fe9e707079ec0d546f3050d3f6c1f8bd", // DOCN · DigitalOcean
  "0x39ec44bee4f6a116c6f9b8de566848a985c53c60", // ELF · e.l.f. Beauty
  "0x1c690498150252222c275a5ced69d3a6b1f52d5e", // EWT · iShares MSCI Taiwan Capped ETF
  "0x7f0abef0c07280f82c6a08ead09ded6bae2c13fc", // EWY · iShares MSCI South Korea fund
  "0x25c288e6d899b9bc30160965ad9644c67e73be0c", // F · Ford Motor
  "0xa48f22a46c0f1c46ca7d111cb6c137c271987180", // FICO · Fair Isaac
  "0x41f4267525a8aff329540ef24fd83d9044758b33", // FIG · Figma
  "0x9ece29a4a2397c0a35fb5fa8ee2b9509130a98cc", // FISV · Fiserv
  "0x93dbb1d2dc5d63f4abacff30485273f538df68ac", // FIX · Comfort Systems
  "0x282e87451e10fa6679bc7d76c69be44cd3fc777c", // FLNC · Fluence Energy
  "0x03bc731ffb162cdd7b98d3c6542bfc291126075d", // FLY · Firefly Aerospace Inc.
  "0x3fb8976980d486084b2eb4a404bd12e72823958f", // FTNT · Fortinet
  "0xeb30663bdff0622ef4e4e5cbb4e975f19f33f51d", // FUTU · Futu Holdings
  "0x63b814ddbd6bf339f25fed8c36158a008d5b373e", // GE · General Electric
  "0x94b8aae43a1ccc08aa64b7d1f29b4d920af4a0c9", // GEV · GE Vernova
  "0xc9a981fee1f9dec688bb123ccdecc63d0debfc4e", // GLD · SPDR Gold Trust
  "0x7c04e6a3368f2a1de3874f0e80d2e0a1a9915da6", // GLW · Corning
  "0x2d427692e928fa156ec22acfabafa0447c5805b7", // GLXY · Galaxy Digital Inc.
  "0x1b0e319c6a659f002271b69db8a7df2f911c153e", // GME · GameStop
  "0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3", // GOOGL · Alphabet Class A
  "0xeb61c0ed490a367d4e3631ccf8a74b3bfc7e775d", // HII · Huntington Ingalls
  "0xccee82fe024c36fa15e1005ede3e9e4787e23d09", // HIMS · Hims & Hers Health
  "0x59dd09d4900c2e4b5f75b7c0d4e6796fcc234cb1", // HPE · HP Enterprise
  "0xaea445c5f3db1a462998ccc422a875a361ee5d99", // HWM · Howmet Aerospace
  "0x980dcf6766fa79f5cf0c4aadb3ab477ff15a9619", // IBM · IBM
  "0x7c148f74ac7445d1f28366b7fcdc6792a9fcd0cf", // IBRX · ImmunityBio,
  "0xacef2e09adb47ad6abebad9ff06689e60615c2b6", // INDA · iShares MSCI India ETF
  "0xb853bc83a753342a4f8320ea680b4b1e84118d21", // INFQ · Infleqtion
  "0xf1953dab6fad537488d5a022361ffaa8b4c95ec6", // INOD · Innodata
  "0xc72b96e0e48ecd4dc75e1e45396e26300bc39681", // INTC · Intel
  "0x56d23bee5f41a7120170b0c603dae30128e460e9", // INTU · Intuit
  "0x558378e000d634a36593e338ebacdd6207640efe", // IONQ · IonQ
  "0xf0ab0c93be6f41369d302e55db1a96b3c430212d", // IREN · IREN Limited
  "0xeaf2512dfc1beac608f8794b3793cd4e02894aa6", // JBL · Jabil Inc.
  "0x03dfbbe0ac4e7bcdafd08ed41a400326b77d8c80", // JNJ · Johnson & Johnson
  "0xb334c5ce741b80b5b671f47f5c269cb193fe8e24", // JOBY · Joby Aviation
  "0x96b933c74ecb4a0926b9210cef7b743ef46be2e9", // KLAC · KLA
  "0x12e3c047bf9aecaf9ddc98c05c31bfd1dd043993", // KSS · Kohls Corporation
  "0x7fd06a4d81ccfa3f351394e144d5191874c31313", // KTOS · Kratos Defense & Security Solutions
  "0x48d60243c66437c6ac3c2495be94747aed5dfe25", // LHX · L3Harris
  "0x8ef20885f94e3d9bc7eb3080279188bd5ed7c08c", // LITE · Lumentum
  "0x8005d266423c7ea827372c9c864491e5786600ea", // LLY · Eli Lilly
  "0x329fcaceb9ad6f9580dd5f643fed0646900d043c", // LMT · Lockheed
  "0x57b0030166db0c31690d1a5aa167e2e26e2c29a4", // LRCX · Lam Research Corp
  "0x4e62068525ab11fe768e29dfd00ef909b9803016", // LULU · Lululemon
  "0xa5d4968421ba94814be3b136b15cf422101ac1a3", // LUNR · Intuitive Machines
  "0xddf2266b79abf0b48898959b0ed6e6adf512be74", // MDB · MongoDB
  "0xc0d6457c16cc70d6790dd43521c899c87ce02f35", // META · Meta Platforms
  "0xc6cbad1016b38b797610c25e1dc7d95988b1f362", // MOD · Modine
  "0x52d50d0280ad1054b43f052bd70a49a212a1b128", // MPWR · Monolithic Power Systems
  "0x43b07d15ce533bec5476d70c22a78a1b2b662155", // MRNA · Moderna
  "0x62fd0668e10d8b72339be2dcf7643001688ff13b", // MRVL · Marvell Technology
  "0xe93237c50d904957cf27e7b1133b510c669c2e74", // MSFT · Microsoft
  "0xec262a75e413fafd0df80480274532c79d42da09", // MSTR · Strategy Inc.
  "0xc93f4d80e268ab922e871bd169156c3cc41894e6", // MTSI · MACOM
  "0xff080c8ce2e5feadaca0da81314ae59d232d4afd", // MU · Micron Technology
  "0x48961813349333209994750ffa89b3c5c22ec969", // MXL · MaxLinear
  "0xf7181b63fdb858558a74ba96bc42732684cd7965", // NAVN · Navan
  "0x9d9c6684f596f66a64c030b93a886d51fd4d7931", // NBIS · Nebius Group
  "0x116f00968269b7bfbad4109ce591d6e74c0601d4", // NET · Cloudflare, Inc. Class A common stock
  "0xe0444ef8bf4ed74f74fd73686e2ddf4c1c5591e8", // NFLX · Netflix
  "0xbef75684c43c4ea7bd18dd532a2244674ee8b926", // NNE · Nano Nuclear Energy
  "0x0c3260af4b8f13a69c4c2dfb84fd667890cdfa14", // NOW · ServiceNow
  "0x408c14038a04f7bd235329e26d2bf569ee20e250", // NU · Nu
  "0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec", // NVDA · NVIDIA
  "0xbe6702d7b70315376dc48a3293f24f0982f86386", // NVTS · Navitas Semiconductor
  "0x8b2f88497f15a18e9d4ffa1a8ffb8538399ae774", // OKLO · Oklo
  "0xbbd09f72b025360fee5c928053dca6248d35be54", // ON · ON Semiconductor
  "0x8ff63eaeee3fe54ba450c4f5538064ec5a893aef", // ONTO · Onto Innovation
  "0xb0992820e760d836549ba69bc7598b4af75dee03", // ORCL · Oracle
  "0x40e7a279850e443f582059ae5dc1c3b6563e6395", // OUST · Ouster
  "0x1cdad396db64bda184d5182a97dd9b3c62100b7d", // P · Everpure
  "0xb039597ed45cba7b6e2fb9e8be51802969cee5be", // PANW · Palo Alto Networks
  "0xfb2664f07b6aadd29ea7a59d8859b1aeb8645cda", // PATH · UiPath
  "0x9b23573b156b52565012f5ce02cdf60afbaa70be", // PENG · Penguin Solutions
  "0x7066a64c24e4206cd62e83bf198c1e7eb361f51e", // PFE · Pfizer
  "0xaa4d64474c172010ab57719cb9951e6142a100d3", // PL · Planet Labs
  "0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a", // PLTR · Palantir Technologies
  "0xcf6b2d875361be807eafa57458c80f28521f9333", // POET · POET Technologies
  "0x237c16d66590f67b886d978acd362eaead8b18c7", // POWL · Powell Industries
  "0x4189f0c66ebbb0bfef1c31f763131361ef32f77c", // PR · Permian Resources
  "0x9ab02ead789b6903c3c44d0ed32f9c707cdf12fd", // PWR · Quanta
  "0xc583c60aef9dc401da72cec1b404743a93cea1cc", // QBTS · D-Wave Quantum Inc. Common Stock
  "0x0f17206447090e464c277571124dd2688e48aea9", // QCOM · Qualcomm
  "0xd5f3879160bc7c32ebb4dc785f8a4f505888de68", // QQQ · Invesco QQQ
  "0x59818904ab4ce163b3ce4ffb64f2d6ca02c434b4", // QUBT · Quantum Computing
  "0xf0c4bf4c582cb3836e98394b1d4e7b7281101be8", // RBLX · Roblox
  "0xfde6b5d9bb419b10c23268c74e369abff39c0460", // RCAT · Red Cat
  "0x05b37fb53a299a1b874a619e1c4c404d52c36f4c", // RDDT · Reddit
  "0x92ef19e82bd8ff36661de838d5eae7e5cef0effe", // RDW · Redwire
  "0x284358abc07f9359f19f4b5b4ac91901be2597ba", // RGTI · Rigetti Computing
  "0xb1bf26c1d20ff267a4f93550d1e0d06ac40a114b", // RIVN · Rivian Automotive
  "0x3b14c39e89d60d627b42a1a4ca45b5bb45fc12e2", // RKLB · Rocket Lab Corporation
  "0x756bc80af765c82da966a788858d65adf14f3793", // RUN · Sunrun
  "0x95052ddcd5dc25641657424a8cf04834997e1730", // SATS · EchoStar
  "0xd63abb2c13d7a8421a8017a712802053568e3c1d", // SCHD · Schwab US Dividend Equity ETF
  "0x92fd66527192e3e61d4ddd13322aa222de86f9b5", // SGOV · iShares 0-3 Month Treasury Bond
  "0xf53f66751b1eff985311b693531e3290f600c410", // SHOP · Shopify
  "0xbe274710bf3d9567e1b290ef6a5f9f90ca016fd8", // SHY · iShares 1-3 Year Treasury Bond ETF
  "0x77e655e37f4d913fb9540e0d541d824171a60e81", // SIMO · Silicon Motion
  "0x84cab63bc87912e71ad199ff14a0ba45de68fef8", // SKHY · SK hynix Inc. American Depositary Shares
  "0x285b231728c7e4333799183df1094d775246a535", // SLS · SELLAS Life Sciences
  "0x411efb0e7f985935daec3d4c3ebaea0d0ad7d89f", // SLV · iShares Silver Trust
  "0xc01aa1fecec0605b13bc84874ff7256c0f5f562a", // SMCI · Super Micro Computer
  "0x072f979c2cac8e1391b0162a87fee094bf8744a0", // SMH · VanEck Semiconductor ETF
  "0x1eebee7f74517e0279dfb09d25b0407beec3fdd6", // SMR · NuScale Power
  "0xf6589f11bc40b669e584073f428b05562f568733", // SNAP · Snap
  "0xb90a19ff0af67f7779aff50a882a9cff42446400", // SNDK · Sandisk Corporation
  "0xba0cab75495255d0cb58e22b648bfed4ecd1f47e", // SNOW · Snowflake
  "0x98e75885157c80992a8d41b696d8c9c6fb30a926", // SOFI · SoFi Technologies
  "0x6e3dfd9f7e1649baa14d25cac18c94d62db10a54", // SOUN · SoundHound AI
  "0x75742c18bc1f1c5c5f448f4c9d9c6f66dafaaa38", // SOXX · iShares Semiconductor ETF
  "0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea", // SPCX · Space Exploration Technologies Corp. Class A Common Stock
  "0xad622320e520de39e72d41ef07438c3fd3354875", // SPMO · Invesco S&P 500 Momentum ETF
  "0x117cc2133c37b721f49de2a7a74833232b3b4c0c", // SPY · SPDR S&P 500 ETF Trust
  "0xb1969f6604ca1ae7a2cd3f1827876e914594ca2d", // TE · T1 Energy
  "0x5b97476b922f3305131b8f0b9d333172e87f4aae", // TEAM · Atlassian Corporation
  "0xb1cc0ec7db69cf43539119814df40071b9d61793", // TEM · Tempus AI
  "0x2778c5024d5ca2cdb0f8ead671ffc69963adcd9c", // TER · Teradyne
  "0x89776d4cd68193597a2fc132cfac1fde36ccea8a", // TSEM · Tower Semiconductor
  "0x322f0929c4625ed5bad873c95208d54e1c003b2d", // TSLA · Tesla
  "0x58ffe4a942d3885baa22d7520691f611ef09e7aa", // TSM · Taiwan Semiconductor Manufacturing
  "0x0b5fb4031cae9163db10b169ee72685f0edc8545", // TTD · Trade Desk
  "0x5e81213613b6b86eab4c6c50d718d34359459786", // TTWO · Take-Two Interactive Software
  "0x0e6e67ba88e7b5d9b67636a215c76779b948de79", // UMC · United Microelectronics
  "0xcf364ea52787e289de6f32077834056e3e70d6a8", // UNH · UnitedHealth
  "0xf23250dac154d05bb671cb0d0ebef3c635c79ce2", // UPS · UPS
  "0xd917b029c761d264c6a312bbbcda868658ef86a6", // USAR · USA Rare Earth
  "0xa30fa36db767ad9ed3f7a60fc79526fb4d56d344", // USO · United States Oil Fund
  "0x6006ed4b2f94110851ff7509d97d034f0eed9226", // VICR · Vicor
  "0xfa78c12e6488814a0262e4e802749a4a737d5fb7", // VRT · Vertiv
  "0x26dcbfb34fc83cabd6990f449674efdc6097ff85", // VSAT · ViaSat
  "0x561e2a49212b7ccf47f2744ccb83e200722fadbc", // VST · Vistra
  "0x0594134df3f171a354d9c85ebd65b7a6148f6d09", // VTI · Vanguard Morningstar Total Stock Market ETF
  "0x82da4646242e1d962e96e932269dc644c94a9caa", // WDAY · Workday
  "0xf52597345a8edf418bc4071b4a35112472277d3e", // WDC · Western Digital
  "0x348be1a8663f15edde5cdf8a96bb69078f7ab6fd", // WULF · TeraWulf
  "0x9e7abd3c9139d14e4c86dce0e455aab7a0c2fb3e", // WYFI · WhiteFiber, Inc.
  "0x15cd20759ce7f3285c29a319de2d1a2e098c6f43", // XLK · State Street Technology Select Sector SPDR ETF
  "0xa8eb3bccbf2017ee7cbfb652eb51cf2e1b153289", // XNDU · Xanadu Quantum
  "0xf9b46d3d1b22199d4d1025a9cedb540a33f1a2d5", // XOM · ExxonMobil Holdings Corporation
  "0x44c4f142009036cf477ed2d09932051843137cf1", // ZM · Zoom
  "0x7dc013eb55e436f30d7ed1afe4e36d6e45e3c3f7", // ZS · Zscaler
]);
