#!/usr/bin/env bash
# Local dev chain: anvil fork of Robinhood Chain mainnet (chainId 4663, real Uniswap v4) + Launchpad contracts.
# Lists every asset in contracts/assets/4663.json at live-price start mcaps (contracts/script/asset-mcaps.mjs) and
# gives anvil accounts #1–#3 some TSLA, USDG and MEME (taken from the PoolManager's balance).
# Writes web/.env.development.local with the deployed addresses (the site indexes the fork itself).
# Seed demo coins and trades afterwards: see contracts/script/Seed.s.sol.
# Usage: scripts/dev-chain.sh            (Ctrl+C stops anvil)
set -euo pipefail
export PATH="$PATH:$HOME/.foundry/bin"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC=http://127.0.0.1:8545
FORK_URL="${RPC_URL_4663:-https://rpc.mainnet.chain.robinhood.com}"

if ! cast chain-id --rpc-url $RPC >/dev/null 2>&1; then
  # --hardfork cancun: skips the EIP-2935 blockhash system call, which needs historical state the public RPC prunes after ~10 min
  anvil --fork-url "$FORK_URL" --port 8545 --host 127.0.0.1 --block-time 1 --hardfork cancun > /tmp/twain-anvil.log 2>&1 &
  ANVIL_PID=$!
  trap 'kill $ANVIL_PID 2>/dev/null' EXIT
  until cast chain-id --rpc-url $RPC >/dev/null 2>&1; do sleep 0.5; done
fi

# anvil default account #0 (public test key — local only)
PK=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
export PROTOCOL_OWNER=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
export PROTOCOL_TREASURY=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
export DEPLOY_NAME=local
# A plain assignment so `set -e` stops here if the price script fails (eval "$(…)" would carry on with no assets).
MCAPS=$(cd "$ROOT/contracts" && node script/asset-mcaps.mjs)
eval "$MCAPS"
START=$(cast block-number --rpc-url $RPC)
(cd "$ROOT/contracts" && forge script script/Deploy.s.sol --rpc-url $RPC --broadcast --private-key $PK >/dev/null)

# 100 TSLA, 10,000 USDG and 1,000,000 MEME each for anvil accounts #1–#3, from the PoolManager (it holds the tokens of
# every v4 pool)
PM=0x8366a39CC670B4001A1121B8F6A443A643e40951
TSLA=0x322F0929c4625eD5bAd873c95208D54E1c003b2d
USDG=0x5fc5360d0400a0fd4f2af552add042d716f1d168
MEME=0x385f4f8ae47651ce5f58f5265395a669f8281e18
cast rpc anvil_impersonateAccount $PM --rpc-url $RPC >/dev/null
cast rpc anvil_setBalance $PM 0x56BC75E2D63100000 --rpc-url $RPC >/dev/null
for A in 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC 0x90F79bf6EB2c4f870365E785982E1f101E93b906; do
  cast send $TSLA "transfer(address,uint256)" $A 100000000000000000000 --from $PM --unlocked --rpc-url $RPC >/dev/null
  cast send $USDG "transfer(address,uint256)" $A 10000000000 --from $PM --unlocked --rpc-url $RPC >/dev/null
  cast send $MEME "transfer(address,uint256)" $A 1000000000000000000000000 --from $PM --unlocked --rpc-url $RPC >/dev/null
done
cast rpc anvil_stopImpersonatingAccount $PM --rpc-url $RPC >/dev/null

J="$ROOT/contracts/deployments/local.json"
get() { python3 -c "import json;print(json.load(open('$J'))['$1'])"; }
LP=$(get launchpad); LOCKER=$(get locker)

cat > "$ROOT/web/.env.development.local" <<ENV
# generated by scripts/dev-chain.sh — local anvil fork
NEXT_PUBLIC_RPC_URL=$RPC
NEXT_PUBLIC_LAUNCHPAD=$LP
NEXT_PUBLIC_LOCKER=$LOCKER
NEXT_PUBLIC_START_BLOCK=$START
ENV
echo "Local chain ready: launchpad $LP  locker $LOCKER  startBlock $START"
echo "Test wallets: import anvil keys from /tmp/twain-anvil.log into your wallet, network RPC $RPC, chainId 4663."
if [ -n "${ANVIL_PID:-}" ]; then wait $ANVIL_PID; fi
